import { Assignment, ClassGroup, Question } from '../types';

export const INITIAL_CLASSES: ClassGroup[] = [
  { id: 'cls-11a1', name: 'Lớp 11A1', code: 'PHY11A1', description: 'Chuyên đề Vật lý nâng cao 11A1' },
  { id: 'cls-11a2', name: 'Lớp 11A2', code: 'PHY11A2', description: 'Khối Khoa học Tự nhiên 11A2' },
  { id: 'cls-11a3', name: 'Lớp 11A3', code: 'PHY11A3', description: 'Khối Tự nhiên 11A3' },
];

export const INITIAL_ASSIGNMENT: Assignment = {
  id: 'asg-chuyende11-daodong',
  title: 'Chuyên đề 11 – Dao động điều hòa và Sóng cơ',
  topic: 'Dao động điều hòa & Sóng cơ (Vật lý 11)',
  description: 'Đề kiểm tra luyện tập tổng hợp gồm 12 câu (8 câu trắc nghiệm MCQ, 2 câu điền số TEXT, 2 câu Đúng/Sai TRUEFALSE). Học sinh làm bài nghiêm túc, chú ý đơn vị.',
  duration_minutes: 20,
  max_attempts: 3,
  shuffle_questions: true,
  shuffle_answers: true,
  status: 'open',
  allowed_class_ids: [], // All classes
  show_solution_mode: 'immediate',
  show_leaderboard: true,
  created_at: new Date(Date.now() - 3600000 * 24 * 2).toISOString(),
};

export const INITIAL_QUESTIONS: Question[] = [
  {
    id: 'q-1',
    assignment_id: 'asg-chuyende11-daodong',
    order_num: 1,
    question_type: 'MCQ',
    question_text: 'Một vật dao động điều hòa theo phương trình x = A*cos(ωt + φ). Đại lượng ω được gọi là gì?',
    option_a: 'Biên độ dao động',
    option_b: 'Chu kỳ dao động',
    option_c: 'Tần số góc của dao động',
    option_d: 'Pha ban đầu của dao động',
    correct_answer: 'C',
    explanation: 'Trong phương trình x = A*cos(ωt + φ), A là biên độ dao động, ω là tần số góc (rad/s), (ωt + φ) là pha dao động ở thời điểm t, và φ là pha ban đầu.',
    score: 1,
  },
  {
    id: 'q-2',
    assignment_id: 'asg-chuyende11-daodong',
    order_num: 2,
    question_type: 'MCQ',
    question_text: 'Vận tốc của một chất điểm dao động điều hòa biến thiên như thế nào so với li độ?',
    option_a: 'Cùng pha với li độ',
    option_b: 'Sớm pha π/2 so với li độ',
    option_c: 'Trễ pha π/2 so với li độ',
    option_d: 'Ngược pha với li độ',
    correct_answer: 'B',
    explanation: 'Ta có v = x\' = -ωA*sin(ωt + φ) = ωA*cos(ωt + φ + π/2). Do đó vận tốc luôn sớm pha hơn li độ một góc π/2 rad.',
    score: 1,
  },
  {
    id: 'q-3',
    assignment_id: 'asg-chuyende11-daodong',
    order_num: 3,
    question_type: 'MCQ',
    question_text: 'Gia tốc của một chất điểm dao động điều hòa đạt giá trị cực đại khi chất điểm ở vị trí nào?',
    option_a: 'Vị trí biên âm',
    option_b: 'Vị trí biên dương',
    option_c: 'Vị trí cân bằng theo chiều dương',
    option_d: 'Vị trí cân bằng theo chiều âm',
    correct_answer: 'A',
    explanation: 'Biểu thức gia tốc: a = -ω²x. Giá trị cực đại a_max = +ω²A đạt được khi x = -A (vị trí biên âm). Độ lớn cực đại đạt ở cả hai vị trí biên.',
    score: 1,
  },
  {
    id: 'q-4',
    assignment_id: 'asg-chuyende11-daodong',
    order_num: 4,
    question_type: 'MCQ',
    question_text: 'Một con lắc lò xo gồm lò xo có độ cứng k và vật có khối lượng m. Tần số góc dao động riêng của con lắc lò xo là:',
    option_a: 'ω = √(k/m)',
    option_b: 'ω = √(m/k)',
    option_c: 'ω = 2π√(k/m)',
    option_d: 'ω = 1/(2π) * √(k/m)',
    correct_answer: 'A',
    explanation: 'Tần số góc dao động tự do của con lắc lò xo được tính theo hệ thức: ω = √(k/m). Chu kỳ T = 2π√(m/k).',
    score: 1,
  },
  {
    id: 'q-5',
    assignment_id: 'asg-chuyende11-daodong',
    order_num: 5,
    question_type: 'MCQ',
    question_text: 'Trong dao động tắt dần, đại lượng nào sau đây giảm dần theo thời gian?',
    option_a: 'Li độ và pha ban đầu',
    option_b: 'Biên độ và cơ năng của hệ',
    option_c: 'Vận tốc cực đại và chu kỳ',
    option_d: 'Tần số và thế năng',
    correct_answer: 'B',
    explanation: 'Do có lực cản của môi trường tiêu hao năng lượng thành nhiệt năng, nên biên độ dao động và cơ năng của hệ giảm dần theo thời gian.',
    score: 1,
  },
  {
    id: 'q-6',
    assignment_id: 'asg-chuyende11-daodong',
    order_num: 6,
    question_type: 'MCQ',
    question_text: 'Hiện tượng biên độ dao động cưỡng bức tăng nhanh đột ngột đến giá trị cực đại khi tần số của ngoại lực cưỡng bức bằng tần số riêng của hệ gọi là:',
    option_a: 'Hiện tượng tự dao động',
    option_b: 'Hiện tượng dao động duy trì',
    option_c: 'Hiện tượng cộng hưởng cơ',
    option_d: 'Hiện tượng dao động tắt dần',
    correct_answer: 'C',
    explanation: 'Hiện tượng cộng hưởng xảy ra khi tần số góc ngoại lực f ≈ f0 (hoặc ω ≈ ω0). Khi đó hệ hấp thụ năng lượng tốt nhất và biên độ đạt cực đại.',
    score: 1,
  },
  {
    id: 'q-7',
    assignment_id: 'asg-chuyende11-daodong',
    order_num: 7,
    question_type: 'MCQ',
    question_text: 'Khoảng cách giữa hai điểm gần nhau nhất trên cùng một phương truyền sóng mà dao động tại hai điểm đó ngược pha nhau là:',
    option_a: 'Một bước sóng (λ)',
    option_b: 'Một nửa bước sóng (λ/2)',
    option_c: 'Một phần tư bước sóng (λ/4)',
    option_d: 'Hai bước sóng (2λ)',
    correct_answer: 'B',
    explanation: 'Độ lệch pha giữa 2 điểm cách nhau khoảng d là Δφ = 2πd/λ. Để ngược pha thì Δφ = (2k+1)π. Khoảng cách gần nhất (k=0) là d = λ/2.',
    score: 1,
  },
  {
    id: 'q-8',
    assignment_id: 'asg-chuyende11-daodong',
    order_num: 8,
    question_type: 'MCQ',
    question_text: 'Điều kiện để xảy ra hiện tượng giao thoa sóng cơ của hai sóng kết hợp là:',
    option_a: 'Cùng tần số, cùng phương và có hiệu số pha không đổi theo thời gian',
    option_b: 'Cùng biên độ và truyền cùng tốc độ trong môi trường',
    option_c: 'Cùng chu kỳ và phát ra từ cùng một vị trí',
    option_d: 'Có năng lượng dao động bằng nhau',
    correct_answer: 'A',
    explanation: 'Hai nguồn sóng kết hợp là hai nguồn cùng tần số, cùng phương dao động và có hiệu số pha không đổi theo thời gian.',
    score: 1,
  },
  {
    id: 'q-9',
    assignment_id: 'asg-chuyende11-daodong',
    order_num: 9,
    question_type: 'TEXT',
    question_text: 'Một con lắc đơn có chiều dài l = 1 m dao động tại nơi có gia tốc trọng trường g = 9,8 m/s². Chu kỳ dao động riêng của con lắc bằng bao nhiêu giây? (Lấy π ≈ 3,14; làm tròn kết quả đến 2 chữ số thập phân)',
    correct_answer: '2.01',
    explanation: 'Công thức chu kỳ con lắc đơn: T = 2π*√(l/g) = 2 * 3,14 * √(1 / 9,8) ≈ 6,28 * 0,3194 ≈ 2,01 s. (Hệ thống chấp nhận cả 2.01, 2,01 hoặc 2.00).',
    score: 1,
  },
  {
    id: 'q-10',
    assignment_id: 'asg-chuyende11-daodong',
    order_num: 10,
    question_type: 'TEXT',
    question_text: 'Một con lắc lò xo có độ cứng k = 100 N/m, gắn với vật nặng m = 0,25 kg. Tính tần số góc dao động ω của con lắc (rad/s)?',
    correct_answer: '20',
    explanation: 'Tần số góc ω = √(k/m) = √(100 / 0,25) = √400 = 20 rad/s.',
    score: 1,
  },
  {
    id: 'q-11',
    assignment_id: 'asg-chuyende11-daodong',
    order_num: 11,
    question_type: 'TRUEFALSE',
    question_text: 'Chu kỳ dao động điều hòa của con lắc đơn phụ thuộc vào khối lượng của quả cầu treo ở đầu con lắc.',
    correct_answer: 'Sai',
    explanation: 'Sai. Chu kỳ con lắc đơn T = 2π√(l/g) chỉ phụ thuộc vào chiều dài dây treo l và gia tốc trọng trường g tại nơi treo, hoàn toàn KHÔNG phụ thuộc vào khối lượng m của vật nặng.',
    score: 1,
  },
  {
    id: 'q-12',
    assignment_id: 'asg-chuyende11-daodong',
    order_num: 12,
    question_type: 'TRUEFALSE',
    question_text: 'Khi sóng cơ truyền từ môi trường này sang môi trường khác (ví dụ từ không khí vào nước), tần số của sóng không thay đổi.',
    correct_answer: 'Đúng',
    explanation: 'Đúng. Khi sóng cơ truyền qua các môi trường khác nhau, tần số dao động f (hoặc chu kỳ T) được quy định bởi nguồn sóng và luôn giữ nguyên không đổi. Chỉ có tốc độ truyền sóng v và bước sóng λ thay đổi.',
    score: 1,
  },
];

export const SECOND_ASSIGNMENT: Assignment = {
  id: 'asg-dien-truong-11',
  title: 'Chuyên đề 11 – Điện trường và Điện thế',
  topic: 'Điện trường & Định luật Coulomb',
  description: 'Bài kiểm tra chuyên đề về lực tương tác tĩnh điện, cường độ điện trường và công của lực điện trường. 10 câu trắc nghiệm nhanh.',
  duration_minutes: 15,
  max_attempts: 2,
  shuffle_questions: true,
  shuffle_answers: true,
  status: 'open',
  allowed_class_ids: [],
  show_solution_mode: 'immediate',
  show_leaderboard: true,
  created_at: new Date(Date.now() - 3600000 * 12).toISOString(),
};

export const SECOND_QUESTIONS: Question[] = [
  {
    id: 'q2-1',
    assignment_id: 'asg-dien-truong-11',
    order_num: 1,
    question_type: 'MCQ',
    question_text: 'Độ lớn lực tương tác tĩnh điện giữa hai điện tích điểm q1, q2 đặt cách nhau khoảng r trong chân không tuân theo định luật nào?',
    option_a: 'Định luật vạn vật hấp dẫn',
    option_b: 'Định luật Coulomb (Cu-lông)',
    option_c: 'Định luật Ôm',
    option_d: 'Định luật Faraday',
    correct_answer: 'B',
    explanation: 'Theo định luật Cu-lông: F = k * (|q1*q2| / r²), với k = 9.10^9 N.m²/C².',
    score: 1,
  },
  {
    id: 'q2-2',
    assignment_id: 'asg-dien-truong-11',
    order_num: 2,
    question_type: 'MCQ',
    question_text: 'Đơn vị đo của cường độ điện trường trong hệ SI là:',
    option_a: 'Vôn (V)',
    option_b: 'Culông (C)',
    option_c: 'Vôn trên mét (V/m)',
    option_d: 'Jun (J)',
    correct_answer: 'C',
    explanation: 'Cường độ điện trường E = F/q = U/d, đơn vị chuẩn trong hệ SI là Vôn trên mét (V/m) hoặc N/C.',
    score: 1,
  },
  {
    id: 'q2-3',
    assignment_id: 'asg-dien-truong-11',
    order_num: 3,
    question_type: 'TRUEFALSE',
    question_text: 'Đường sức điện của một điện tích điểm dương là những đường thẳng có chiều hướng ra xa điện tích.',
    correct_answer: 'Đúng',
    explanation: 'Đúng. Đường sức điện trường tĩnh luôn đi ra từ điện tích dương và kết thúc ở điện tích âm (hoặc ở vô cực).',
    score: 1,
  },
  {
    id: 'q2-4',
    assignment_id: 'asg-dien-truong-11',
    order_num: 4,
    question_type: 'TEXT',
    question_text: 'Hằng số điện môi ε của môi trường chân không bằng bao nhiêu?',
    correct_answer: '1',
    explanation: 'Đối với chân không, hằng số điện môi ε = 1 (không khí khô cũng xấp xỉ bằng 1).',
    score: 1,
  },
];
